hc_nodes:
  hosts:
    host1.example.com:
      gluster_infra_volume_groups:
        - vgname: vg_sdb
          pvname: /dev/mapper/vdo_sdb
      gluster_infra_mount_devices:
        - path: /gluster_bricks/engine
          lvname: gluster_lv_engine
          vgname: vg_sdb
        - path: /gluster_bricks/data
          lvname: gluster_lv_data
          vgname: vg_sdb
      gluster_infra_cache_vars:
        - vgname: vg_sdb
          cachedisk: /dev/sdc
          cachelvname: cachelv_thinpool_vg_sdb
          cachethinpoolname: thinpool_vg_sdb
          cachelvsize: 18G
          cachemetalvsize: 2G
          cachemetalvname: cache_thinpool_vg_sdb
          cachemode: writethrough
      gluster_infra_vdo:
        - name: vdo_sdb
          device: /dev/sdb
          logicalsize: 1000G
      gluster_infra_vdo_blockmapcachesize: 128M
      gluster_infra_vdo_slabsize: 2G
      gluster_infra_vdo_readcachesize: 20M
      gluster_infra_vdo_readcache: enabled
      gluster_infra_vdo_writepolicy: auto
      gluster_infra_vdo_emulate512: 'on'
      gluster_infra_thick_lvs:
        - vgname: vg_sdb
          lvname: gluster_lv_engine
          size: 100G
      gluster_infra_thinpools:
        - vgname: vg_sdb
          thinpoolname: thinpool_vg_sdb
      gluster_infra_lv_logicalvols:
        - vgname: vg_sdb
          thinpool: thinpool_vg_sdb
          lvname: gluster_lv_data
          lvsize: 100G
    host2.example.com:
      gluster_infra_volume_groups:
        - vgname: vg_sdb
          pvname: /dev/mapper/vdo_sdb
      gluster_infra_mount_devices:
        - path: /gluster_bricks/engine
          lvname: gluster_lv_engine
          vgname: vg_sdb
        - path: /gluster_bricks/data
          lvname: gluster_lv_data
          vgname: vg_sdb
      gluster_infra_cache_vars:
        - vgname: vg_sdb
          cachedisk: /dev/sdc
          cachelvname: cachelv_thinpool_vg_sdb
          cachethinpoolname: thinpool_vg_sdb
          cachelvsize: 18G
          cachemetalvsize: 2G
          cachemetalvname: cache_thinpool_vg_sdb
          cachemode: writethrough
      gluster_infra_vdo:
        - name: vdo_sdb
          device: /dev/sdb
          logicalsize: 1000G
      gluster_infra_vdo_blockmapcachesize: 128M
      gluster_infra_vdo_slabsize: 2G
      gluster_infra_vdo_readcachesize: 20M
      gluster_infra_vdo_readcache: enabled
      gluster_infra_vdo_writepolicy: auto
      gluster_infra_vdo_emulate512: 'on'
      gluster_infra_thick_lvs:
        - vgname: vg_sdb
          lvname: gluster_lv_engine
          size: 100G
      gluster_infra_thinpools:
        - vgname: vg_sdb
          thinpoolname: thinpool_vg_sdb
      gluster_infra_lv_logicalvols:
        - vgname: vg_sdb
          thinpool: thinpool_vg_sdb
          lvname: gluster_lv_data
          lvsize: 100G
    host3.example.com:
      gluster_infra_volume_groups:
        - vgname: vg_sdb
          pvname: /dev/mapper/vdo_sdb
      gluster_infra_mount_devices:
        - path: /gluster_bricks/engine
          lvname: gluster_lv_engine
          vgname: vg_sdb
        - path: /gluster_bricks/data
          lvname: gluster_lv_data
          vgname: vg_sdb
      gluster_infra_cache_vars:
        - vgname: vg_sdb
          cachedisk: /dev/sdc
          cachelvname: cachelv_thinpool_vg_sdb
          cachethinpoolname: thinpool_vg_sdb
          cachelvsize: 18G
          cachemetalvsize: 2G
          cachemetalvname: cache_thinpool_vg_sdb
          cachemode: writethrough
      gluster_infra_vdo:
        - name: vdo_sdb
          device: /dev/sdb
          logicalsize: 1000G
      gluster_infra_vdo_blockmapcachesize: 128M
      gluster_infra_vdo_slabsize: 2G
      gluster_infra_vdo_readcachesize: 20M
      gluster_infra_vdo_readcache: enabled
      gluster_infra_vdo_writepolicy: auto
      gluster_infra_vdo_emulate512: 'on'
      gluster_infra_thick_lvs:
        - vgname: vg_sdb
          lvname: gluster_lv_engine
          size: 100G
      gluster_infra_thinpools:
        - vgname: vg_sdb
          thinpoolname: thinpool_vg_sdb
      gluster_infra_lv_logicalvols:
        - vgname: vg_sdb
          thinpool: thinpool_vg_sdb
          lvname: gluster_lv_data
          lvsize: 100G
  vars:
    gluster_infra_stripe_unit_size: 256
    gluster_infra_disktype: JBOD
    gluster_infra_diskcount: 12
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
local:
  hosts:
    localhost: null
  vars:
    gluster_features_hci_volumes:
      - volname: engine
        brick: /gluster_bricks/engine/engine
        arbiter: false
        master: localhost
      - volname: data
        brick: /gluster_bricks/data/data
        arbiter: false
        master: localhost
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
