- name: Setup backend and deploy HCI
  hosts: hc_nodes
  remote_user: root
  gather_facts: yes

  vars:
    gluster_features_hci_packages: []
    gluster_features_hci_cluster: "{{ groups['hc_nodes'] }}"
    gluster_infra_lv_thinpoolname: gluster_thinpool

  roles:
     - gluster.infra
     - gluster.features
