---
# Warning: This playbook assumes that the information in the inventory is correct
# and performs naive shell commands using those values as inputs.
# Use only if you are sure that the values in the inventory don't coincide with
# anything that you don't want cleaned up.

- hosts: local
  tasks:
    - name: Delete the volumes
      shell: glustercli volume stop {{ item.volname }};glustercli volume delete {{ item.volname }} -y
      register: shell_output
      changed_when: shell_output.rc == 0
      #failed_when False
      with_items:
        - "{{ gluster_features_hci_volumes }}"
      tags:
        - delete_volumes
    - name: Remove the peers
      shell: glustercli peer remove $(glustercli peer list|grep {{ item }}|awk '{ print $2; }')
      register: shell_output
      changed_when: shell_output.rc == 0
      #failed_when False
      with_inventory_hostnames:
        - hc_nodes
      tags:
        - remove_peers
- name: Remove brick setup
  hosts: hc_nodes
  tasks:
    - name: Unmount and delete bricks
      shell: umount {{ item.path }};e=$?; rm -rf  {{ item.path }};exit $e
      register: shell_output
      changed_when: shell_output.rc == 0
      failed_when: False
      with_items:
        - "{{ gluster_infra_mount_devices }}"

    - name: Wipe filesystem from LVs
      shell: wipefs -a /dev/{{ item.vgname }}/{{ item.lvname}}
      register: shell_output
      changed_when: shell_output.rc == 0
      #failed_when False
      with_items:
        - "{{ gluster_infra_mount_devices }}"

    - name: Remove VG
      shell: vgremove {{ item.vgname }} -ff
      register: shell_output
      changed_when: shell_output.rc == 0
      with_items: "{{ gluster_infra_volume_groups }}"
      when: gluster_infra_volume_groups is defined
      #failed_when False
    - name: Remove VDO
      shell: vdo remove -n {{ item.name }}
      register: shell_output
      changed_when: shell_output.rc == 0
      #failed_when False
      with_items:
        - "{{ gluster_infra_vdo }}"
      when: gluster_infra_vdo is defined
  tags:
    - cleanup_bricks
