hc_nodes:
  hosts:
    host1.example.com:
      gluster_infra_lv_thicklvname: gluster_lv_engine
      gluster_infra_lv_thicklvsize: gluster_lv_100
      gluster_infra_vdo:
        - name: vdo_sdc
          device: /dev/sdc
          logicalsize: 200G
      gluster_infra_vdo_blockmapcachesize: 128M
      gluster_infra_vdo_slabsize: 32G
      gluster_infra_vdo_readcachesize: 20M
      gluster_infra_vdo_readcache: enabled
      gluster_infra_vdo_writepolicy: auto
      gluster_infra_vdo_emulate512: 'on'
      gluster_infra_pvs:
        - /dev/sdb
        - /dev/vdo_sdc
      gluster_infra_lv_logicalvols:
        - lvname: gluster_lv_data
          lvsize: 100G
      gluster_infra_mount_devices:
        - path: /gluster_bricks/engine
          lv: gluster_lv_engine
        - path: /gluster_bricks/data
          lv: gluster_lv_data
    host2.example.com:
      gluster_infra_lv_thicklvname: gluster_lv_engine
      gluster_infra_lv_thicklvsize: gluster_lv_100
      gluster_infra_vdo:
        - name: vdo_sdx
          device: /dev/sdx
          logicalsize: 205G
      gluster_infra_vdo_blockmapcachesize: 128M
      gluster_infra_vdo_slabsize: 32G
      gluster_infra_vdo_readcachesize: 20M
      gluster_infra_vdo_readcache: enabled
      gluster_infra_vdo_writepolicy: auto
      gluster_infra_vdo_emulate512: 'on'
      gluster_infra_pvs:
        - /dev/sdb
        - /dev/vdo_sdx
      gluster_infra_lv_logicalvols:
        - lvname: gluster_lv_data
          lvsize: 100G
      gluster_infra_mount_devices:
        - path: /gluster_bricks/engine
          lv: gluster_lv_engine
        - path: /gluster_bricks/data
          lv: gluster_lv_data
    host3.example.com:
      gluster_infra_lv_thicklvname: gluster_lv_engine
      gluster_infra_lv_thicklvsize: gluster_lv_100
      gluster_infra_vdo:
        - name: vdo_sdc
          device: /dev/sdc
          logicalsize: 200G
      gluster_infra_vdo_blockmapcachesize: 128M
      gluster_infra_vdo_slabsize: 32G
      gluster_infra_vdo_readcachesize: 20M
      gluster_infra_vdo_readcache: enabled
      gluster_infra_vdo_writepolicy: auto
      gluster_infra_vdo_emulate512: 'on'
      gluster_infra_pvs:
        - /dev/sdb
        - /dev/vdo_sdc
      gluster_infra_lv_logicalvols:
        - lvname: gluster_lv_data
          lvsize: 100G
      gluster_infra_mount_devices:
        - path: /gluster_bricks/engine
          lv: gluster_lv_engine
        - path: /gluster_bricks/data
          lv: gluster_lv_data
  vars:
    gluster_infra_stripe_unit_size: 256
    gluster_infra_disktype: JBOD
    gluster_infra_diskcount: 12
    gluster_features_hci_volumes:
      - volname: engine
        brick: /gluster_bricks/engine/engine
        arbiter: false
      - volname: data
        brick: /gluster_bricks/data/data
        arbiter: false
